//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpChat
    {
        public int HelpChatID { get; set; }
        public string Message { get; set; }
        public int FromID { get; set; }
        public int ToID { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
