//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int AccountID { get; set; }
        public string ReceiverPhone { get; set; }
        public Nullable<System.DateTime> TransferTime { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ServiceID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Service Service { get; set; }
    }
}
